language: minimal

git:
  submodules: false

services:
  - docker

before_install:
  - git submodule update --init metslib
  - docker-compose build
  - docker-compose up -d mariadb clamav
  - docker-compose run test bin/setup_dev.sh

script:
  - docker-compose run test
