language: perl

git:
  submodules: false

services:
  - docker

before_install:
  - git submodule update --init metslib
  - docker build . -t hathitrust/feed:test

script:
  - docker run hathitrust/feed:test bash -c 'HTFEED_CONFIG=/usr/local/feed/etc/config_test.yml perl -I lib -w t/001_load.t'
