version: '3'

services:

  sut:
    build: .
    environment:
      - HTFEED_CONFIG=/usr/local/feed/etc/config_test.yml
      - FEED_HOME=/usr/local/feed
      - TEST=1
    command: bash -c "perl Makefile.PL && bin/wait-for --timeout=300 mariadb:3306 minio:9000 -- make test TEST_VERBOSE=1"
    depends_on:
      - mariadb
      - minio

  mariadb:
    build: docker/database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot

  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: TESTINGACCESSKEY
      MINIO_SECRET_KEY: testingsecretkey
    command: server /data
