version: '3'

services:

  sut:
    build: .
    environment:
      - HTFEED_CONFIG=/usr/local/feed/etc/config_test.yml
      - FEED_HOME=/usr/local/feed
      - TEST=1
      - VERSION=feed-testing
    command: bash -c "bin/wait-for --timeout=300 mariadb:3306 minio:9000 pushgateway:9091 rabbitmq:5672 -- prove -I lib"
    depends_on:
      - mariadb
      - minio
      - pushgateway
      - rabbitmq

  sut-submodule:
    build: .
    environment:
      - HTFEED_CONFIG=/usr/local/feed/etc/config_test.yml
      - FEED_HOME=/usr/local/feed
      - TEST=1
      - VERSION=feed-testing
    command: bash -c "prove -I lib t/submodules"

  mariadb:
    build: docker/database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot

  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: TESTINGACCESSKEY
      MINIO_SECRET_KEY: testingsecretkey
    command: server /data

  pushgateway:
    image: prom/pushgateway
    command:
      - --web.enable-admin-api

  rabbitmq:
    image: rabbitmq
