ARG image_tag=ghcr.io/hathitrust/feed-full-unstable:latest
FROM ${image_tag}
LABEL org.opencontainers.image.source https://github.com/hathitrust/feed

ARG version=feed-production
ENV VERSION=$version
