
GRANT USAGE ON *.* TO 'feed'@'%' IDENTIFIED BY 'feed';
GRANT SELECT, INSERT, UPDATE, DELETE, LOCK TABLES ON `ht`.* TO 'feed'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, LOCK TABLES ON `handle`.* TO 'feed'@'%';
