---

#########################################
# DATABASE CONFIGURATION
#########################################

# Set $mysql if using a mysql database or $sqlite otherwise.
database: $sqlite

# Configuration for using a SQLite database. This is the default and 
# recommended for prevalidation work. You should not need to change
# anything in this section.
sqlite:
  datasource: "dbi:SQLite:dbname=$feed_var/db/feed.db"
  username: ""
  password: ""

# Configure this section if using a MySQL database (suggested if running 
# feed processes simultaneously on multiple machines.)
mysql:
  # The Perl DBI DSN to use when connecting with mysql. See perldoc DBD::mysql.
  datasource: dbi:mysql:ht:mysql-sdr
  # The username used to connect to the database.
  username: ht_repository
  # The password used to connect to the database.
  password: $database_password

#########################################
# PATHS TO EXTERNAL PROGRAMS
#########################################

# Set to the path to 'convert' from ImageMagick version 6.5.4 or later.
imagemagick: /usr/bin/convert

# Set to the path to the jhove binary and configuration. This MUST be
# JHOVE 1.6 or later -- JHOVE 1.5 and earlier reports image metadata in an incompatible fashion.
jhove: /usr/bin/jhove
jhoveconf: /etc/jhove/jhove.conf

# You will need to build validateCache using $feed_home/src/make (requires that
# the Xerces-C libraries and headers be installed.) While a schema cache is
# distributed with feed you may need to rebuild it. Test it by trying to
# validate an XML file: in the $feed_home/bin, run
#   ./validateCache ../etc/schema.cache somefile.xml 
# (where somefile.xml is a test file to validate). If it doesn't work, try just
# running: 
#   ./validateCache somefile.xml
# if that works, remove schema.cache and rebuild by running
#   ./validateCache -save ../etc/schema.cache somefile.xml.

xerces: $feed_bin/validateCache
xerces_cache: $feed_etc/schema.cache

# path to kdu_compress from kakadu 6.4 - the version is important because
# different versions of kakadu interpret compression settings differently.
# Leave blank if you don't have kakadu.
kdu_compress: ~
# Set to the path to kdu_munge if you have it. Otherwise leave this blank.
# (kdu_munge can remediate certain kinds of JPEG2000 problems)
kdu_munge: ~

# path to mp3val
mp3val: ~


#########################################
# WORKING DIRECTORIES
#########################################

# Set this to the base working directory for feed, for example /tmp/feed.
staging_root: $feed_var/stage
# Set to the base directory for fetching volumes that feed will work on. Each package
# type should have a subdirectory in this directory. For example, if you have a directory with
# files to work on called:
#   /htprep/mypackagetype/31234012345678
# then you should set sip_root to /htprep.
sip_root: $feed_var/prep

# Leave this as-is.
staging:
  # each package type will have a separate fetch directory
  fetch: $sip_root
  ingest: $staging_root/ingest
  zip: $staging_root/zip
  zipfile: $staging_root/zipfile
  preingest: $staging_root/preingest
  marc: $sip_root/marc


#########################################
# PREMIS TOOL CONFIGURATION
#########################################

# A perl snippet returning the software name and version for each 'tool' code
# in the PREMIS events below. $self is the HTFeed::METS stage generating the
# PREMIS events.

premis_tools:
# Leave as-is.
  GROOVE: $FindBin::Script . " " . HTFeed::Version::get_vstring();
# Leave as-is.
  EXIFTOOL: perl_mod_version('Image::ExifTool');
# Set to the version of Xerces you are using (must be 3.0 or later) 
  XERCES: qq(Xerces-C 3.1)
  JHOVE: qq(JHOVE 1.11)
# Leave as is.
  DIGEST_MD5: perl_mod_version('Digest::MD5');
# GnuPG is not needed unless downloading packages from Google.
  GPG: qq(GnuPG 2)
# Set to the version of zip you are using (recommended: 3.0 or later with ZIP64
# support)
  ZIP: qq(Zip 3.0)
# feed is only compatible with Kakadu 6.4.0 or later
  KDU_COMPRESS: qq(kdu_compress 6.4.0)
  EPUBCHECK: qq(epubcheck 4.0.2)
  MP3VAL: qq(mp3val 0.1.8)
  CLAMAV: qq(ClamAV 0.102.3)


#########################################
# MISCELLANEOUS CONFIGURATION
#########################################

# Lists the value to use for the metsHdr agent name element.
# Set to the name of your organization or organizational unit
mets_header_agent_name: HathiTrust
# value to use for the METS PROFILE attribute
mets_profile: http://www.hathitrust.org/documents/hathitrust-mets-profile2.1.xml

# Logging configuration - leave as-is.

l4p:
  root_logger: 'INFO, file'
  config: $feed_etc/config.l4p

# List of states where feed/litefeed/RunLite should stop - leave as is.
release_states:
  - punted
  - done

stop_file: $feed_etc/STOPFEED
