stop_on_error: 0

realdb: ht

storage_classes:
  localpairtree-ingest:
    class: HTFeed::Storage::LinkedPairtree
    # The directory in which symbolic links will be created to each volume
    link_dir: /sdr1/obj
    # The directory into which volumes will be loaded
    obj_dir: /sdr2/obj
  prefixedversions-ingest:
    class: HTFeed::Storage::PrefixedVersions
    obj_dir: /htdataden

repository:
  # The directory in which symbolic links will be created to each volume
  link_dir: /sdr1/obj
  # The directory into which volumes will be loaded
  obj_dir: /sdr2/obj

handle:
  repo_url_base: https://babel.hathitrust.org/cgi/pt?id=
  root_admin: 0.NA/9999
  local_admin: 9999/invalid
  database:
    datasource: dbi:mysql:handle:mariadb
    username: feed
    password: feed

rabbitmq:
  host: rabbitmq
  user: guest
  password: guest
  queue: ingest
  priority_levels: 3

volumes_in_process_limit: 1

use_dropbox: 1
rclone_config_path: /usr/local/feed/etc/rclone.conf

pushgateway: http://pushgateway:9091

zephir_ftps_server: ftps
zephir_submissions_path: ""

rights:
  rights_dir: /usr/local/feed/var/rights
