---
database:
  datasource: dbi:mysql:my_db:mysql-sdr
  password: password
  username: uname
jhove: /l/local/bin/jhove
jhoveconf: /l/local/jhove/conf/jhove.conf
l4p_config: /htapps/rrotter.babel/git/feed/etc/config.l4p
staging_directory: /htapps/ezbrooks.babel/GROOVE_2.0/break_GRIN/test/undamaged
staging:
  disk: /htapps/rrotter.babel/repos/staging
  memory: /ram/staging
key_directory: /sdr1/etc/g/groove