feed_home: /usr/local/feed
# shouldn't actually be used
repository:
  # The directory in which symbolic links will be created to each volume
  link_dir: /tmp/obj
  # The directory into which volumes will be loaded
  obj_dir: /tmp/obj

staging_root: /tmp/prevalidate
sip_root: /tmp/stage

kdu_compress: /usr/local/bin/kdu_compress

stop_on_error: 0

sqlite:
  datasource: "dbi:SQLite:dbname=/tmp/feed.db"
  username: ""
  password: ""

xerces: /usr/local/feed/blib/bin/validateCache
epubcheck: /usr/bin/java -jar /usr/bin/epubcheck
