---
database:
  datasource: dbi:mysql:mdp_tracking_rrotter:mysql-htdev
  username: rrotter
  password: xxxx

jhove: /l/local/bin/jhove
jhoveconf: /l/local/jhove/conf/jhove.conf

xerces: /path/to/xerces

jhove: /l/local/bin/jhove
jhoveconf: /l/local/jhove/conf/jhove.conf
l4p_config: /htapps/rrotter.babel/git/feed/etc/config.l4p

staging:
  disk: /htapps/rrotter.babel/repos/staging
  memory: /ram/staging
  zip: /ram/zip_staging
  
sample_directory: /htapps/rrotter.babel/repos/samples
repository_path: /htapps/rrotter.babel/repos
  
handle:
  repo_url_base: http://babel.hathitrust.org/cgi/pt?id=
  root_admin: 0.NA/2027
  local_admin: 2027/mdp
  database:
    datasource: dbi:mysql:handle:mysql-htdev
    username: handle
    password: xxxx

###### PREMIS configuration ######################################################
#
# A perl snippet returning the software name and version for each 'tool' code in the
# PREMIS events below. $self is the HTFeed::METS stage generating the PREMIS events.

premis_tools:
    GROOVE: $self->git_revision();
    EXIFTOOL: $self->perl_mod_version('Image::ExifTool');
    XERCES: $self->local_directory_version('xerces-c');
    JHOVE: $self->local_directory_version('jhove');
    DIGEST_MD5: $self->perl_mod_version('Digest::MD5');
    GPG: $self->system_version('gnupg');
    ZIP: $self->local_directory_version('zip');

# Location of the symlinks for 'local directory version'
premis_tool_local: /l/local

# For each possible kind of PREMIS event, list the 
# PREMIS eventType, the eventDetail, the executor linkingAgent (should be UM or
# VOLUME_ARTIST), and any tool linkingAgents. The tools must be drawn from
# the list in the 'tools' configuration variable here.

premis_events:

  capture:
    type: capture
    detail: Initial capture of item
    executor: VOLUME_ARTIST

  ht_mets_creation:
    type: mets creation
    detail: Creation of HathiTrust METS file
    executor: UM
    tools:
    - GROOVE

  image_compression:
    type: image compression
    detail: Conversion of raw scans to compressed TIFF and JPEG2000
    # executor is package-type specific
    # tools is package-type specific

  image_header_modification:
    type: image header modification
    detail: Modification of image headers to meet HathiTrust conventions
    executor: UM
    tools:
    - GROOVE
    - EXIFTOOL

  ingestion:
    type: ingestion
    detail: Ingestion of object package into repository
    executor: UM
    tools:
    - GROOVE

  mets_validation:
    type: validation
    detail: Validation of source METS file
    executor: UM
    tools:
    - XERCES

  ocr_normalize:
    type: ocr split
    # detail is package-type specific
    executor: UM
    tools:
    - GROOVE

  package_validation:
    type: validation
    detail: Validation of object components
    executor: UM
    tools:
    - GROOVE
    - JHOVE
    - XERCES

  page_feature_mapping:
    type: page feature mapping
    detail: Mapping of original page feature tags to HathiTrust tags
    executor: UM
    tools:
    - GROOVE

  page_md5_create:
    type: message digest calculation
    detail: Calculation of page-level MD5 checksums
    executor: UM
    tools:
    - DIGEST_MD5

  page_md5_fixity:
    type: fixity check
    detail: Validation of page-level MD5 checksums
    executor: UM
    tools:
    - DIGEST_MD5

  preingest:
    type: transformation
    detail: Transformation of files for ingest (mod1-modN in source METS)
    executor: UM
    tools:
    - GROOVE
    # list any other tools here??

  source_md5_fixity:
    type: fixity check
    detail: Validation of MD5 checksums for downloaded file archives
    executor: UM
    tools:
    - DIGEST_MD5

  source_mets_creation:
    type: source mets creation
    detail: Creation of source METS file
    executor: UM
    tools:
    - GROOVE

  zip_compression:
    type: zip compression
    detail: Compression of content files and source METS into zip archive
    executor: UM
    tools:
    - ZIP

  zip_md5_create:
    type: zip file message digest calculation
    detail: Calculation of md5 checksum for zip archive
    executor: UM
    tools:
    - DIGEST_MD5

