feed_home: /usr/local/feed

staging_root: /tmp/stage
sip_root: /tmp/sips

kdu_compress: /usr/local/bin/kdu_compress

stop_on_error: 0

database:
  # The Perl DBI DSN to use when connecting with mysql. See perldoc DBD::mysql.
  datasource: dbi:mysql:ht:mariadb
  # The username used to connect to the database.
  username: feed
  # The password used to connect to the database.
  password: feed

rights:
# Database with the rights_current table
  database: dbi:mysql:ht:mariadb
  # The username used to connect to the database.
  username: feed
  # The password used to connect to the database.
  password: feed

# Location of rights files
  rights_dir: $feed_var/rights
# Where to archive rights files after they are loaded
  archive: $rights_dir/archive

realdb: ht

xerces: /usr/local/feed/blib/bin/validateCache
epubcheck: /usr/bin/java -jar /usr/bin/epubcheck

storage_classes:
  - class: HTFeed::Storage::LocalPairtree
    # The directory in which symbolic links will be created to each volume
    link_dir: /sdr2/obj
    # The directory into which volumes will be loaded
    obj_dir: /sdr1/obj
  - class: HTFeed::Storage::PrefixedVersions
    obj_dir: /htdataden

jhove: /usr/bin/jhove
jhoveconf: /etc/jhove/jhove.conf
