repository:
  # The directory in which symbolic links will be created to each volume
  link_dir: /nonexistent
  # The directory into which volumes will be loaded
  obj_dir: /nonexistent

sip_root: /tmp
stop_on_error: 0
