---
name: Manual Image Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: true

jobs:
  build_manual:
    runs-on: ubuntu-latest
    steps:
      - uses: hathitrust/github_actions/build@v1
        with:
          image: ghcr.io/hathitrust/feed-unstable
          tag: ${{ github.event.inputs.tag }}
          push_latest: false
          build-args: 'version="commit ${{ github.sha }}"'
          registry_token: ${{ github.token }}
