name: Run CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # This should be a PAT that has read access to the private submodules
          # for this repository
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true

      - name: Build docker image
        run: docker-compose --file docker-compose.test.yml build

      - name: Run tests
        run: docker-compose --file docker-compose.test.yml run sut

      - name: Run tests for submodules
        run: docker-compose --file docker-compose.test.yml run sut-submodule
