---
name: Run CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker compose --file docker-compose.test.yml build

      - name: Run tests
        run: docker compose --file docker-compose.test.yml run sut
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
