name: Docker Tag Latest Release

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag latest image and push to GHCR
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/hathitrust/feed:${{ github.event.release.tag_name }}
          ghcr.io/hathitrust/feed:latest
        file: Dockerfile.prod
        build-args: |
          version=${{ github.event.release.tag_name }}
          image_tag=ghcr.io/hathitrust/feed-unstable:${{ github.sha }}

    - name: Build and tag latest full image and push to GHCR
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/hathitrust/feed-full:${{ github.event.release.tag_name }}
          ghcr.io/hathitrust/feed-full:latest
        file: Dockerfile.prod
        build-args: |
          version=${{ github.event.release.tag_name }}
          image_tag=ghcr.io/hathitrust/feed-full-unstable:${{ github.sha }}
