name: Tag Latest Image with Release Version

on:
  release:
    types: [released]

jobs:
  tag-release:
    name: Tag Release
    uses: hathitrust/github_actions/.github/workflows/tag-release.yml@70aa6270dd1555f0e52bff3d7894ecdb7c76f80f # v2.1.1
    with:
      existing_tag: ghcr.io/${{ github.repository }}:${{ github.sha }}
      image: ghcr.io/${{ github.repository }}
      new_tag: ${{ github.event.release.tag_name }}
    secrets: inherit
