name: Tag Latest Image with Release Version

on:
  release:
    types: [released]

jobs:
  tag-release:
    name: Tag Release
    uses: hathitrust/github_actions/.github/workflows/tag-release.yml@dc1e0d1e000e898af7ac65b5ecb1e3f7d9fd1dcc # v2.1.0
    with:
      existing_tag: ghcr.io/${{ github.repository }}:${{ github.sha }}
      image: ghcr.io/${{ github.repository }}
      new_tag: ${{ github.event.release.tag_name }}
    secrets: inherit
