name: Docker Tag Latest Release

on:
  release:
    types: [ released ]
  workflow_dispatch:

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: hathitrust/github_actions/tag-release@action-updates
        with:
          registry_token: ${{ github.token }}
          existing_tag: ghcr.io/hathitrust/feed-unstable:${{ github.sha }}
          image: ghcr.io/hathitrust/feed
          new_tag: ${{ github.event.release.tag_name }}
